image: php:7.1.9-fpm
pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$FTP_SERVER_ADDRESS/var/www/html