image: php:7.1.9-fpm
pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - echo "TESTING > ftp://$FTP_SERVER_ADDRESS/var/www/html"
          - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://138.68.185.55/var/www/html