image: php:7.1.9-fpm
pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - echo "TESTING > $FTP_SERVER_ADDRESS"
          - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$FTP_SERVER_ADDRESS/var/www/html